---
title: "Onderzoek naar habitatgebruik van bever (_Castor fiber_) in relatie tot schadebeheer."
author: 
  - 
    name: "Frank Huysentruyt"
    email: "frank.huysentruyt@inbo.be"
  - 
    name: "Kristof Baert"
    email: "kristof.baert@inbo.be"
  - 
    name: "Jim Casaer"
    email: "jim.casaer@inbo.be"
  - 
    name: "Joris Vernaillen"
    email: "joris.vernaillen@inbo.be"
  - 
    name: "Jan Vercammen"
    email: "jan.vercammen@inbo.be"
    
subtitle: "Verkenning van het ruimtegebruik voorafgaand aan beheermaatregelen"
reportnr: ""
ordernr: ""
link-citations: TRUE
bibliography: literatuurlijst.bib
site: bookdown::bookdown_site
output:
  bookdown::gitbook:
    split_by: "chapter+number"
    template: !expr INBOmd::inbo_rapport_css("html")
  bookdown::pdf_book:
    base_format: INBOmd::inbo_rapport
  bookdown::epub_book:
    stylesheet: "css/inbo_rapport.css"
    template: !expr INBOmd::inbo_rapport_css("epub")
---

```{r setup, include=FALSE}
library(tidyverse)
library(readxl)
library(rgdal)
library(inborutils)
library(leaflet)
library(rgeos)
library(geosphere)
library(maptools)
library(kableExtra)
library(raster)
#library(mapview)
#library(raster)
library(knitr)
opts_chunk$set(
  echo = FALSE, 
  eval = TRUE,
  cache = FALSE,
  dpi = 300,
  fig.width = 150 / 25.4,
  fig.height = 100 / 25.4,
  warning = TRUE,
  error = TRUE,
  message = TRUE
)
library(INBOtheme)
theme_set(
  theme_inbo(
    base_family = "Calibri", # "Flanders Art Sans",
    base_size = 12
  )
)
if (!interactive() && opts_knit$get("rmarkdown.pandoc.to") != "html") {
  opts_chunk$set(dev = "cairo_pdf")
  theme_set(
    theme_inbo(
      base_family = "Calibri", # "Flanders Art Sans",
      base_size = 8
    )
  )
}
```

```{r, data inlezen, include=FALSE}
##gegevens importeren uit excel databank telemetrie
Bevers <- read_excel('input/Zenderdatabank.xlsx', sheet = "Vangstgegevens")
Jongen <- read_excel('input/Zenderdatabank.xlsx', sheet = "Voortplanting")
Burchten <- read_excel('input/Zenderdatabank.xlsx', sheet = "Burchten")
Fotos <- read_excel('input/Zenderdatabank.xlsx', sheet = "Cameravalfotos")
##gegevens inventarisatierondes 2017
InventApril <- read_excel('input/Inventarisaties.xlsx', sheet = "April")
InventAug <- read_excel('input/Inventarisaties.xlsx', sheet = "Augustus")
##gegevens uit naar csv omgezette kml files uit Mymaps samennemen in telemetriefile
fileNames <- Sys.glob(file.path("input/csv","*.csv"))
Telemetrie <- NULL
for (fileName in fileNames) {
  tmp <- read.csv2(fileName, header=TRUE)
  Telemetrie <- rbind(Telemetrie,tmp)
}
##verwijder tijdelijke files
remove(tmp,fileName,fileNames)
```

```{r, datacleaning, include=FALSE}
#Grids definieren
BEL <- "+init=epsg:31370"
WGS84 <- "+init=epsg:4326"

#dataformats
#Bevers
Bevers$Bever <- as.factor(Bevers$Bever)
Bevers$Geslacht <- as.factor(Bevers$Geslacht)
#Burchten
Burchten$Burcht <- as.factor(Burchten$Burcht)
Burchten$Bever <- as.factor(Burchten$Bever)
#Fotos
Fotos$Bever <- as.factor(Fotos$Bever)
Fotos$Datum <- paste(Fotos$Datum," ",substr(Fotos$Uur,12,19))
Fotos$Datum <- strptime(Fotos$Datum, format="%Y-%m-%d %H:%M:%S")
Fotos$Uur <- NULL
#Inventarisaties
InventApril$Type <- as.factor(InventApril$Type)
InventAug$Type <- as.factor(InventAug$Type)
#Telemetrie
Telemetrie$Bever <- as.factor(Telemetrie$Bever)
Telemetrie$Date <- paste(Telemetrie$Datum," ",Telemetrie$Uur)
Telemetrie$Datum <- strptime(Telemetrie$Date, format="%d/%m/%Y %H:%M:%S")
Telemetrie$Uur <- NULL
#Alle waarnemingen samen
Waarnemingen <- rbind(Telemetrie[,c(4,1,3,2)],Fotos)
Waarnemingen$Datumkort <- as.Date(Waarnemingen$Datum, format="%d/%m/%Y")
##Dataset met enkel gezenderde bevers
Zenderbevers <- Bevers %>% 
  filter(!is.na(Frequentie)) %>% 
  droplevels()
```

```{r, afstanden, include=FALSE}
##maximale afstanden berekenen per beest
x <- 0
Afstanden <- data.frame(Bever=factor(levels(Waarnemingen$Bever)),
                        maxdist=as.numeric(rep("", length(levels(Waarnemingen$Bever)))))
for (i in levels(Waarnemingen$Bever)){
  tmp <- subset(Waarnemingen, Bever==i)
  for (j in 1:(nrow(tmp)-1)){
    for (k in 1:(nrow(tmp)-j)){
      y <- pointDistance(tmp[j,c("lon","lat")],tmp[j+k,c("lon","lat")], lonlat=T)
      if(y>x){
        x<-y
      }
    }
  }
Afstanden$maxdist[Afstanden$Bever==i] <- x
x <- 0
}

##verwijder tijdelijke files
remove(i,j,k,x,y)
```

# {-}

# Dankwoord {-}

Tekst.

# Voorwoord {-}

Tekst. 


# Samenvatting {-}

Tekst

**Vette tekst.**

# Aanbevelingen voor beheer en/of beleid {-}

-	Tekstpunt 1
-	Tekstpunt 2 _'cursieve tekst'_ 

# English abstract {-}

\benglish

English text.

\eenglish

\mainmatter

# Inleiding

##Algemeen kader

De Europese bever, _Castor fiber_ (hierna _bever_), ...tekst.